apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: hello-microsoft
        image: service-b:latest
        args:
          - "-text=Hello Microsoft!"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10