apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-b-role
  namespace: default  # Change to the appropriate namespace if necessary
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
